### ISSUE TITLE
Update session expiration after reading cookies from http

### ISSUE THREAD

**Issue by Kiratmee** [PC-fit-Christian-Rupp/Crypt-Cookie#23]
line 36:
if "HTTP_COOKIE" in os.environ:
	self.__cookie = cookies.SimpleCookie(os.environ["HTTP_COOKIE"])
	**self.__updateSessionExpirationTime()**
else:
	self.__newCookie()

expiration is not transmitted from browser to server. To set the expiration date to the database, it has to be newly calculated and set in the cookie, so the server can access the data

**Comment by zeroconf1970** [comment]
Wrong usage! Expiration as an additional cookie to session information added.
